// GENERATED by the host on 2026-09-17. Do not hand-edit.
//
// WHY THIS IS NOT THE APP'S DOCUMENTS DIRECTORY.
//
// Loading from Documents is already proven: the Debug run did exactly that and
// initLlama returned in 36.4 s. It is not repeatable for a Release build,
// because `xcrun simctl install` rotates the Data container UUID on EVERY
// install, measured three times this session:
//     ADEC8507 -> 304E8CF4 -> E2789BED
// Documents contents migrate with the app, so the model survives, but a Release
// build embeds its JS bundle at build time. Baking in the container path means
// the path is stale the moment the build is installed, and the only way to fix
// it is to rebuild, which requires another install, which rotates again.
//
// llama.rn does not resolve relative paths: `src/index.ts` only strips a
// `file://` prefix and passes the rest through, so an absolute path is required
// and there is no runtime Documents API in RN core to build one from.
//
// This path is outside the container and therefore stable. It changes nothing
// about the measurement: tok/s does not depend on which directory the GGUF sits
// in, and the file is byte-identical to the one in Documents.
//
// THE REAL APP NEEDS A RUNTIME PATH. A tiny native module returning
// NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, ...) removes this
// whole problem, and the shell should have one before it ships a model.
export const MODEL_PATH =
  '/Users/virajbagga/Coding/steel26/03-model/base/NVIDIA-Nemotron3-Nano-4B-Q4_K_M.gguf';
